# Generated by Django 6.0 on 2025-12-09 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='is_used',
            field=models.CharField(default='unused', max_length=10),
        ),
        migrations.AlterField(
            model_name='voucherbatch',
            name='prefix',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
