# Generated by Django 6.0 on 2025-12-09 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0002_alter_voucher_is_used_alter_voucherbatch_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='is_used',
            field=models.CharField(choices=[('unused', 'غير مستخدم'), ('used', 'مستخدم'), ('expired', 'منتهي')], default='unused', max_length=10),
        ),
    ]
