# Generated by Django 6.0 on 2025-12-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0004_voucherbatch_distributer'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='token',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
