# Generated by Django 6.0 on 2026-01-20 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0005_voucher_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers', to='vouchers.voucherbatch'),
        ),
    ]
