# Generated by Django 6.0 on 2026-01-20 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0005_alter_offer_duration_type_alter_offer_quota_type'),
        ('vouchers', '0006_alter_voucher_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offers.offer'),
        ),
        migrations.AlterField(
            model_name='voucherbatch',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='offers.offer'),
        ),
    ]
