# Generated by Django 6.0 on 2026-01-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vouchers', '0007_alter_voucher_offer_alter_voucherbatch_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='sold_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
