# Generated by Django 6.0 on 2025-12-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price_display', models.CharField(max_length=20)),
                ('number_of_clients', models.IntegerField()),
                ('number_of_servers', models.IntegerField()),
                ('number_of_vouchers', models.IntegerField()),
            ],
        ),
    ]
