# Generated by Django 6.0 on 2025-12-06 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='description',
        ),
    ]
