# Generated by Django 6.0 on 2025-12-10 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_remove_plan_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('bank_name', models.CharField(max_length=20)),
                ('bank_account', models.CharField(max_length=20)),
                ('bank_account_holder', models.CharField(max_length=20)),
                ('bank_account_number', models.CharField(max_length=20)),
            ],
        ),
    ]
