# Generated by Django 6.0 on 2025-12-13 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_techsupport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='techsupport',
            name='bank_account',
            field=models.CharField(default='123456789', max_length=20),
        ),
        migrations.AlterField(
            model_name='techsupport',
            name='bank_account_holder',
            field=models.CharField(default='Tech Support', max_length=20),
        ),
        migrations.AlterField(
            model_name='techsupport',
            name='bank_account_number',
            field=models.CharField(default='123456789', max_length=20),
        ),
        migrations.AlterField(
            model_name='techsupport',
            name='bank_name',
            field=models.CharField(default='Bank', max_length=20),
        ),
        migrations.AlterField(
            model_name='techsupport',
            name='name',
            field=models.CharField(default='Tech Support', max_length=50),
        ),
        migrations.AlterField(
            model_name='techsupport',
            name='phone',
            field=models.CharField(default='0123456789', max_length=20),
        ),
    ]
