# Generated by Django 6.0 on 2025-12-13 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_alter_techsupport_bank_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techsupport',
            name='bank_account',
        ),
    ]
