# Generated by Django 6.0 on 2025-12-14 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_remove_techsupport_bank_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='techsupport',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tech_support_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='techsupport',
            name='bank_account_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
