# Generated by Django 6.0 on 2025-12-14 19:00

from django.db import migrations, models

def populate_username_password(apps, schema_editor):
    TechSupport = apps.get_model('adminpanel', 'TechSupport')
    for row in TechSupport.objects.all():
        # Provide a unique username relative to the ID to satisfy unique constraint
        row.username = f"tech_support_{row.id}"
        row.password = "12345678" # Default placeholder password
        row.save()

class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_techsupport_user_and_more'),
    ]

    operations = [
        # 1. Add fields as nullable first
        migrations.AddField(
            model_name='techsupport',
            name='username',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='techsupport',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
        # 2. Populate data
        migrations.RunPython(populate_username_password, reverse_code=migrations.RunPython.noop),
        
        # 3. Alter to enforce constraints (unique, non-null)
        migrations.AlterField(
            model_name='techsupport',
            name='username',
            field=models.CharField(max_length=50, unique=True, default="default_tech"), # default needed for strict mode sometimes, but rows are populated
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='techsupport',
            name='password',
            field=models.CharField(max_length=20, default="12345678"),
            preserve_default=False,
        ),
        
        # 4. Finally remove the old user field
        migrations.RemoveField(
            model_name='techsupport',
            name='user',
        ),
    ]
