# Generated by Django 6.0 on 2025-12-14 19:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_remove_techsupport_user_techsupport_password_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='techsupport',
            name='password',
        ),
        migrations.RemoveField(
            model_name='techsupport',
            name='username',
        ),
        migrations.AddField(
            model_name='techsupport',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tech_support_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='techsupport',
            name='bank_account_holder',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='techsupport',
            name='bank_account_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='techsupport',
            name='bank_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='techsupport',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
