# Generated by Django 6.0 on 2025-12-14 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0008_remove_techsupport_password_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    def set_default_users(apps, schema_editor):
        TechSupport = apps.get_model('adminpanel', 'TechSupport')
        CustomUser = apps.get_model('account', 'CustomUser')
        for tech in TechSupport.objects.filter(user__isnull=True):
            # Generate a unique username based on ID or Name
            username = f"techsupport_{tech.id}"
            # Ensure uniqueness
            count = 1
            while CustomUser.objects.filter(username=username).exists():
                username = f"techsupport_{tech.id}_{count}"
                count += 1
            
            user = CustomUser.objects.create(
                username=username,
                password="password123", # Temporary password
                is_staff=False,
                is_superuser=False
            )
            tech.user = user
            tech.save()

    operations = [
        migrations.RunPython(set_default_users, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='techsupport',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tech_support_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
