# Generated by Django 6.0 on 2025-12-17 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_alter_techsupport_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='number_of_clients',
        ),
    ]
