# Generated by Django 6.0 on 2025-12-12 05:33

import design.validate
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('background_image', models.ImageField(default='media/designs/backgrounds/card_background.jpg', upload_to='designs/', validators=[design.validate.validate_image, design.validate.validate_image_size])),
                ('serial_x', models.IntegerField(default=50)),
                ('serial_y', models.IntegerField(default=80)),
                ('serial_font_size', models.IntegerField(default=18)),
                ('serial_color', models.CharField(default='#000000', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
