# Generated by Django 6.0 on 2025-12-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='serial_x',
            field=models.IntegerField(default=70),
        ),
        migrations.AlterField(
            model_name='design',
            name='serial_y',
            field=models.IntegerField(default=100),
        ),
    ]
