# Generated by Django 6.0 on 2025-12-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_alter_design_serial_x_alter_design_serial_y'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/previews/'),
        ),
    ]
