# Generated by Django 6.0 on 2025-12-14 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_customuser_created_at'),
        ('adminpanel', '0006_techsupport_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tech_support_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resellers', to='adminpanel.techsupport'),
        ),
    ]
