# Generated by Django 6.0 on 2025-12-14 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_customuser_tech_support_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_paied',
            field=models.BooleanField(default=True),
        ),
    ]
