# Generated by Django 6.0 on 2025-12-05 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('hostname', models.CharField(max_length=200)),
                ('api_user', models.CharField(max_length=150)),
                ('api_password', models.CharField(max_length=200)),
                ('api_port', models.PositiveIntegerField(default=8728)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
