# Generated by Django 6.0 on 2025-12-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='api_user',
        ),
        migrations.RemoveField(
            model_name='server',
            name='description',
        ),
        migrations.RemoveField(
            model_name='server',
            name='hostname',
        ),
        migrations.AddField(
            model_name='server',
            name='serial_number',
            field=models.CharField(default=''),
        ),
    ]
