# Generated by Django 6.0 on 2025-12-07 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0002_remove_server_api_user_remove_server_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='api_port',
        ),
    ]
