# Generated by Django 6.0 on 2025-12-18 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_remove_server_api_port'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='api_password',
        ),
        migrations.RemoveField(
            model_name='server',
            name='serial_number',
        ),
        migrations.AddField(
            model_name='server',
            name='hostname',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='server',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
