# Generated by Django 6.0 on 2026-01-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_remove_server_api_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='last_heartbeat',
            field=models.DateTimeField(blank=True, default='1970-01-01 00:00:00', null=True),
        ),
    ]
