# Generated by Django 6.0 on 2026-01-18 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0005_server_last_heartbeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='tunnel_ip',
            field=models.GenericIPAddressField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='server',
            name='tunnel_password',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
