# Generated by Django 6.0 on 2025-12-05 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unlimited_speed', models.BooleanField(default=False)),
                ('download_speed', models.PositiveIntegerField(blank=True, null=True)),
                ('upload_speed', models.PositiveIntegerField(blank=True, null=True)),
                ('speed_formula', models.BooleanField(default=False)),
                ('duration_type', models.CharField(choices=[('hours', 'ساعات'), ('days', 'أيام'), ('months', 'شهور')], max_length=20)),
                ('duration_value', models.PositiveIntegerField()),
                ('quota_type', models.CharField(choices=[('none', 'غير محدود'), ('monthly', 'شهري'), ('fixed', 'محددة (جيجا)')], max_length=20)),
                ('quota_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('block_porn_sites', models.BooleanField(default=False)),
                ('peak_time', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
