# Generated by Django 6.0 on 2025-12-07 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='block_porn_sites',
            field=models.BooleanField(default=False, verbose_name='حجب المواقع الإباحية'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='download_speed',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='سرعة التحميل'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='duration_type',
            field=models.CharField(choices=[('hours', 'ساعات'), ('days', 'أيام'), ('months', 'شهور')], max_length=20, verbose_name='نوع المدة'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='duration_value',
            field=models.PositiveIntegerField(verbose_name='المدة'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='متاح'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم العرض'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='peak_time',
            field=models.BooleanField(default=False, verbose_name='وقت الذروة'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='quota_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='كمية الكوتا'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='quota_type',
            field=models.CharField(choices=[('none', 'غير محدود'), ('monthly', 'شهري'), ('fixed', 'محددة (جيجا)')], max_length=20, verbose_name='نوع الكوتة'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='speed_formula',
            field=models.BooleanField(default=False, verbose_name='تفعيل معادلة السرعة'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='unlimited_speed',
            field=models.BooleanField(default=False, verbose_name='سرعة مفتوحة'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='upload_speed',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='سرعة الرفع'),
        ),
    ]
