# Generated by Django 6.0 on 2025-12-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_alter_offer_block_porn_sites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='quota_type',
            field=models.CharField(choices=[('none', 'غير محدود'), ('fixed', 'محددة (جيجا)')], max_length=20, verbose_name='نوع الكوتة'),
        ),
    ]
