# Generated by Django 6.0 on 2025-12-17 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributers', '0001_initial'),
        ('offers', '0003_alter_offer_quota_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='distributer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='distributers.distributer'),
        ),
    ]
