# Generated by Django 6.0 on 2026-01-07 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_offer_distributer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='duration_type',
            field=models.CharField(choices=[('minutes', 'دقائق'), ('hours', 'ساعات'), ('days', 'أيام'), ('months', 'شهور')], max_length=20, verbose_name='نوع المدة'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='quota_type',
            field=models.CharField(choices=[('none', 'غير محدود'), ('MB', 'ميجابايت'), ('fixed', 'محددة (جيجا)')], max_length=20, verbose_name='نوع الكوتة'),
        ),
    ]
