# Generated by Django 6.0 on 2025-12-17 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servers', '0003_remove_server_api_port'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('can_view_offers', models.BooleanField(default=False)),
                ('can_add_offer', models.BooleanField(default=False)),
                ('can_edit_offer', models.BooleanField(default=False)),
                ('can_delete_offer', models.BooleanField(default=False)),
                ('can_view_designs', models.BooleanField(default=False)),
                ('can_add_design', models.BooleanField(default=False)),
                ('can_delete_design', models.BooleanField(default=False)),
                ('can_view_vouchers', models.BooleanField(default=False)),
                ('can_add_voucher', models.BooleanField(default=False)),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributers_created', to=settings.AUTH_USER_MODEL)),
                ('servers', models.ManyToManyField(blank=True, related_name='distributers', to='servers.server')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='distributer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
