# Generated by Django 6.0 on 2025-12-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RadAcct',
            fields=[
                ('radacctid', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64, null=True)),
                ('acctstarttime', models.DateTimeField(null=True)),
                ('acctstoptime', models.DateTimeField(null=True)),
                ('framedipaddress', models.CharField(max_length=15, null=True)),
                ('acctsessiontime', models.BigIntegerField(null=True)),
                ('callingstationid', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'radacct',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RadCheck',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64)),
                ('attribute', models.CharField(max_length=64)),
                ('op', models.CharField(max_length=2)),
                ('value', models.CharField(max_length=253)),
            ],
            options={
                'db_table': 'radcheck',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RadReply',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64)),
                ('attribute', models.CharField(max_length=64)),
                ('op', models.CharField(max_length=2)),
                ('value', models.CharField(max_length=253)),
            ],
            options={
                'db_table': 'radreply',
                'managed': False,
            },
        ),
    ]
